### ISSUE TITLE
Support for the `Error` class in the `.error` method

### ISSUE THREAD

**Issue by clemenzi** [pietrodev07/kittylog#7]
Add support for the Node.js Internal class `Error`, an example of how the `.error` method would become could be:

```js
kittylog.error(new Error("Something happened"));
```

It can be useful to send errors using the `Error` class but keeping a nice style in the console.

I don't think about just having the method accept `Error` classes but make it possible, an example of type in typescript would be:

```ts
function error(...args: string | Error): void
```
(I am sure kittylog does not support infinite arg but in pr #4 was proposed)

I can make a pull request for this feature.

**Comment by pietrodev07** [comment]
Great idea, you can add it. Thanks!
