### ISSUE TITLE
Performance method improvement

### ISSUE THREAD

**Issue by olga-demina** [pietrodev07/kittylog#9]
The performance method as it is now doen't give any real idea about the performance of code execution. I would suggest to implement it similar to console.time method.
https://www.w3schools.com/Jsref/met_console_time.asp

**Describe the solution you'd like**
It could be implemented like this: 
```
kittylog.performance('loading data...')
  // code execution
kittylog.performanceEnd()

```
expected result in console:
`[PERFORMANCE] loading data... - Time taken: 1.00s
`

**Comment by pietrodev07** [comment]
Great idea! It's neat and useful! 
Will you make this improvement or should I?

**Comment by olga-demina** [comment]
I would be happy to make it
